---
# tasks file for tests
#- name: Get start timestamp
#  set_fact:
#    starttime: "{{ ansible_data_time }}"

- name: Create image  
  os_image:
      state: present
      auth: "{{ auth }}"
      region_name: "{{ test_env.region_name }}"
      availability_zone: "{{ test_env.availability_zone }}"
      validate_certs: False
      name: cirros
      container_format: bare
      disk_format: qcow2
      state: present
      filename: cirros-0.3.5-x86_64-disk.img
      kernel: cirros-vmlinuz
      ramdisk: cirros-initrd
      properties:
        cpu_arch: x86_64
        distro: ubuntu

- name: Create network
  os_network:
      state: present
      auth: "{{ auth }}"
      validate_certs: False
      name: test
      external: no

- name: Create subnet
  os_subnet:
      state: present
      auth: "{{ auth }}"
      #validate_cert: False
      network_name: test
      name: test-subnet
      cidr: 192.168.113.0/24
      dns_nameservers:
          - 8.8.8.8

- name: Create router
  os_router:
      state: present
      auth: "{{ auth }}"
      validate_certs: False
      name: test_router
      network: ext-net
      interfaces:
          - test-subnet
            # - ext-subnet

- name: Create test flavor
  os_nova_flavor:
      state: present
      auth: "{{ auth }}"
      region_name: "{{ test_env.region_name }}"
      availability_zone: "{{ test_env.availability_zone }}"
      validate_certs: False
      name: test
      ram: 512
      vcpus: 1
      disk: 5
      ephemeral: 0
      
- name: Create key-pair
  os_keypair:
      state: "present"
      auth: "{{ auth }}"
      region_name: "{{ test_env.region_name }}"
      availability_zone: "{{ test_env.availability_zone }}"
      validate_certs: False
      name: "openstack-tests"
      public_key_file: "{{ test_env.public_key_file }}"

- name: Create security group
  os_security_group:
      state: present
      auth: "{{ auth }}"
      region_name: "{{ test_env.region_name }}"
      availability_zone: "{{ test_env.availability_zone }}"
      validate_certs: False
      name: test_sg
      description: security group for testing

- name: Add security rules
  os_security_group_rule:
      state: present
      auth: "{{ auth }}"
      region_name: "{{ test_env.region_name }}"
      availability_zone: "{{ test_env.availability_zone }}"
      validate_certs: False
      security_group: test_sg
      protocol: tcp
      direction: ingress
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0

- name: Create test node
  os_server:
      state: present
      auth: "{{ auth }}"
      region_name: "{{ test_env.region_name }}"
      availability_zone: "{{ test_env.availability_zone }}"
      validate_certs: False
      name: test
      image: "cirros"
      key_name: "openstack-tests"
      timeout: 200
      flavor: test
      network: test
      security_groups: test_sg
      floating_ip_pools: "{{ test_env.public_net_name | default(omit) }}"
      meta:
          hostname: test

- include: cinder.yml
  when: "{{ test_env.enable_cinder }}"
